### ISSUE TITLE
View profile doesn't render correctly

### ISSUE THREAD

**Issue by annie** [lazerwalker/azure-mud#100]
After clicking on someone's username, their profile is overlaid with the chat, making it unreadable. Perhaps it could be opened in an absolutely positioned modal, or appear in the left sidebar.

![Screen Shot 2020-08-13 at 22 54 18](https://user-images.githubusercontent.com/6464196/90265297-5f745280-de20-11ea-8013-c7478ce57f3a.png)

**Comment by lazerwalker** [comment]
For some context, the original design idea was for it to look like Slack's profile screen — so, in a right-hand sidebar that isn't visible unless a profile is open, and in a way that doesn't obstruct people from seeing the main chat window.

I'm not opposed to it being a modal, though.

**Comment by kawa-kitsuragi** [comment]
(Feel free to swap tags or take out the milestone if needed, but these seemed right!)

**Comment by lazerwalker** [comment]
Worth calling out that we now have a proper reusable modal view system (you can see it with the profile edit view if you're already registered, or if you check out the post-it note wall in the kitchen). 

I wonder if it might make sense for the profile view where this lives to be one of the new modals instead of living as a sidebar?

I legitimately don't know which I think would be best, both have positives and negatives! But worth calling out that making it a proper modal dialog is a much easier option than it was a few days ago.

**Comment by annie** [comment]
hmm originally i thought a modal would be best, but now i'm not sure.

if we plan to show 1:1 chats in the sidebar, perhaps clicking on a username should just open a 1:1 chat with that person, with their profile info always showing at the top of the chat? that might be what you were already describing in https://github.com/lazerwalker/azure-mud/issues/17 😅

i'll try implementing something tonight & send it over to see what y'all think. would you mind adding me as a collaborator so i can self-assign?

**Comment by lazerwalker** [comment]
Added you as a collaborator and assigned to you :)

Yeah, that was my thought in #17! Your call whichever you think makes the most sense to play with in terms of a modal vs a sidebar.
