### ISSUE TITLE
Profile links, and links in chat, should open in a new window

### ISSUE THREAD

**Issue by mgritter** [lazerwalker/azure-mud#197]
Clicking on a twitter or website link in a profile navigates away from the MUD window; these links should be target="_blank", I think?

I'll see if I can open a PR for this.

**Comment by mgritter** [comment]
Oops, Twitter links are fine, they already have the target.

**Comment by lazerwalker** [comment]
That would be awesome if you wanted to look into this!

For some context, the underlying issue seems to be the library we're using to automatically detect and link-ify links: https://github.com/tasti/react-linkify

For chat links (although not the profile links, I don't think) we're currently specifying `target="_blank"`, although there's obviously something wrong with either the way we're doing this or the library: https://github.com/lazerwalker/azure-mud/blob/main/src/components/MessageView.tsx#L70
