### ISSUE TITLE
Noah didn't always show up as a mod to me

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/azure-mud#202]
He was consistently a mod in his profile, but his NameView was inconsistently colored. Maybe inconsistent data in the redis minimal profile vs full profile?

**Comment by kawa-kitsuragi** [comment]
Alexei and I noticed similar behavior too - both looking at ourselves and at one point at each other.

**Comment by MoyTW** [comment]
I'm pretty sure this has to do with user data not matching server when somebody gets made a mod. If you go into the Profile/whisper view it should show people as mods properly. I think it's because Profile and the Name views pull their data from distinct sets and somehow the user data in the users map doesn't have that info (it goes as undefined).

Repro steps (requires 2 accounts one of which starts as mod):
* mod the second account
* have the second account type something
* inspect them in profile
* de-mod the second account
* inspect them in Profile

I ran across this doing something completely different. Pics:
![Screenshot from 2020-09-23 20-22-18](https://user-images.githubusercontent.com/1434086/94098147-d49e5480-fddc-11ea-9808-1005cd5351ca.png)
![Screenshot from 2020-09-23 20-23-55](https://user-images.githubusercontent.com/1434086/94098144-d405be00-fddc-11ea-84d6-ea0f632dce72.png)
![Screenshot from 2020-09-23 20-24-02](https://user-images.githubusercontent.com/1434086/94098143-d405be00-fddc-11ea-991d-402f6cdaa14b.png)
![Screenshot from 2020-09-23 20-24-19](https://user-images.githubusercontent.com/1434086/94098142-d36d2780-fddc-11ea-9fb7-4e81c55f06fb.png)
![Screenshot from 2020-09-23 20-25-36](https://user-images.githubusercontent.com/1434086/94098140-d2d49100-fddc-11ea-9892-46bb134734a2.png)

**Comment by lazerwalker** [comment]
Hoping the fix to #279 fixes this. We'll need to un-mod and re-mod everyone to see if it fixes this.

**Comment by lazerwalker** [comment]
That fix works for Britta. We should all test this together Saturday morning or earlier. Again, affected mods will need to be un-modded and re-modded.
