### ISSUE TITLE
A dedicated way to specify "this is a question for the speaker"

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/azure-mud#207]
Alexei was struggling to find which chat messages were questions. Let people flag them!

**Comment by lazerwalker** [comment]
The lazy version of this is throwing up a note wall in the theatre, but we'll presumably need a way to wipe that out after every speaker.

Still thinking about what a better 'proper' solution might be.

**Comment by MoyTW** [comment]
Maybe a `/speaker` or `/question` or some-such command that either just makes the message really distinct or sends to a new modal?

**Comment by lazerwalker** [comment]
The more I think about this, the more I like the idea of just using a note wall. We've got a built-in persistent viewing UI, we've got a way for attendees to vote up questions other attendees have asked. We just need an admin 'delete all' button to wipe the wall after each talk, and someone to actually do that.

**Comment by lazerwalker** [comment]
@apepers Since you're the person with the most direct experience here from the preview, I wanted to get your thoughts! 

Travis just added https://github.com/lazerwalker/azure-mud/pull/250, with the idea being that people will just use the note wall to leave dedicated speaker questions, and it'll be someone's job (the StreamYard tech person? A mod? The emcee?) to wipe the questions after each talk ends. 

Gut check about this as a plan?

**Comment by apepers** [comment]
My gut check is that's fine and could be part of the MC job - because I did have chat open at the same time in the theatre to be able to otherwise interact with the room or see questions. A single button to wipe all of the questions would be nice, to save the individual clicks. If we label it in the room and it also gets added to the MC spiel of 'whenever it's question time remind people to use the note wall for questions' then I think it should be easy to direct people towards.

Only potential problem would be if opening the notewall hides the view of the speaker, for if people are asking a question while it's going. Might be nice to have a shortcut like the /speaker or /question option that just results in a note being created, as an alternate flow.

**Comment by lazerwalker** [comment]
There's now a "pop out stream" link underneath the video that opens up a separate window with both the Twitch stream + captions. I strongly suspect a plurality or majority of users will end up using that — agree that having a /command would be nice, but now probably lower priority for that specific use case.
