### ISSUE TITLE
People weren't really chatting in non-theatre rooms. How do we fix this?

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/azure-mud#214]
To me, it is still a major design pillar of the space that it should be able to facilitate small group conversations among people who don't know each other.

The current design isn't accomplishing this. In a few cases, I was able to start up conversation by asking an ice-breaker question, but for the most part people would just go into another room with 3-8 people and then not say anything.

A few thoughts about what we could do:

- Make room titles/descriptions more evocative: the "study" is where you go to talk about academia, etc
- More explicit game design-themed rooms. e.g. you go to the "proc-gen parlor" to talk about procgen. I don't like being so didactic here, but this would likely work very effectively.
- More game-like mechanics to act as hooks for people to talk to each other. Two people needing to interact with the same object in a room to progress in a quest can lead to conversation
- Explicit ice-breakers to suggest chat questions to open people up. This could be room descriptions suggesting specific questions for people to ask each other, or e.g. a bot that detects if nobody's spoken in X minutes and injects an ice-breaker question
- More aggressive on-boarding. People were weirded out by the unfamiliar (i.e. not Discord/Slack/IRC) model of only being in one room at a time. More hand-holding is likely needed to get people used to how this works, why it exists, etc.
- Remove the ephemeral room model entirely in favor of a traditional Discord/Slack channel model. I think this largely represents failure towards the specific design goal of small group conversations, but is an option.
- Find a way to let people easily be both in the theatre and a small room, so they can participate in small conversations without feeling FOMO over the big chat room. This would be sort of a step closer back towards Discord/Slack without fully conceding the idea that there can be chat spaces with smaller numbers of people. See below for more on this.

Some related but different issues:
- We're putting room player counts back in the sidebar, they weren't visible enough in the chat. Letting people more aggressively self-balance and easily go to where discussions are happening may help.
- Some people wanted to be able to be in multiple rooms at once, a la Discord/Slack. I think en masse this breaks the design goal of small conversations, but designs to help facilitate this (e.g. the app supports opening multiple windows, even if we don't build out intentional UI to make this easy) can help particularly active chatters be in more discussions at once, helping everyone.

Would love other people's thoughts here!

**Comment by MoyTW** [comment]
One thing to note is that I think basically zero people interacted with the greeting room. 99% of it was "Person pops in, either immediately leaves or waits around a bit, completely silent, before leaving." And to be honest, in order to interact in the greeting room you need to first figure out a bunch of stuff about how it works - like the person who wrote "What happens if I type something in here?" into the chat.

So, I'm now of the strong opinion that we should do a explainer popup when somebody first logs in or registers.

`for the most part people would just go into another room with 3-8 people and then not say anything.` this is how chat programs have trained users to act. I mean...that's what the vast majority of people do in Discord - lurk. I think we're swimming upstream really, really hard against this.

* `More aggressive on-boarding.` I think the main issue is it looks a bit more like a traditional chat program but doesn't really behave like it, and so absent any explanation it's just very confusing, and it's close enough that you could reasonably squint at it and go "...but, why not Discord?" - the sidebar looks like it's trying to be Discord. One way to solve this would be to remove the channels, and force map navigation, to basically outright say "Treat this as a game world not a chat program" - but then you're being very draconian with your usage. I don't know if that's what we want to do, and I don't know if it would trigger a change in habits.

* I think an explicit "talk to me" flag might be helpful? but the usability on that is kind of crazy, and you have to have people knowing what it is before it works. As per above, "being on video" is effectively a "talk to me" flag. A big difference in real/virtual conversations is in real conversations you can tell when you have somebody's attention. You can't really here, so it's really weird to start a conversation when somebody comes into the room because half the time they're just like, touring, and they tour faster than you can type. And then when you say something they might not respond and then they just leave and ??? - that felt kind of awful. Video actually acted very differently here because you knew when somebody was in a call with you - they've opted into conversation at that point. Merely entering a room does not indicate conversational intent, but video does.

I think "creating a setting that encourages people to initiate conversations" is better than the "literally just initiate conversations for them" mechanics like games/a parrot bot, but I think we those are still good ideas.

* `More game-like mechanics to act as hooks for people to talk to each other.` Yeah.
* `a bot that detects if nobody's spoken in X minutes and injects an ice-breaker question` I kind of hate coffeebot at work and after the first two weeks everybody ignored it, but at our program only runs two days. So I think that's possible.

I don't think we should just bin it and go with Discord, that feels like you'd just have the exact same problem. I think the vast majority of Discord servers with people who do not already know each other personally have a very low participation ratio so it would be easier, but not better.

**Comment by lazerwalker** [comment]
That's a really good point about the modal. I'm usually hesitant for that didactic onboarding, but I think a single screen would help. I'll draft up some text and add a one-time modal. 

Would also be curious to hear from @phildini about his thoughts about how the greeter room worked/didn't work!

**Comment by phildini** [comment]
I think one thing that might help is if each room had something you could _only_ do in that room.
Like, maybe there's a special piece of info you can only change in the greeting room? Or you have to interact with the greeters to get some virtual swag?

This might make it so people interact there more, and might be a good dry-run for proving you know how to navigate the space?

**Comment by lazerwalker** [comment]
Added a separate issue (and PR) for a welcome modal: https://github.com/lazerwalker/azure-mud/issues/242

Technical gotcha is it currently shows up any time you move to the entryway, which may be minorly annoying for greeters (sorry!).

**Comment by lazerwalker** [comment]
That's a really good point about finding something to actually do in the greeting room! Could even be as simple as (a) having to say something to the greeter and (b) clicking a button or typing a command to pick up your name badge off the table.

**Comment by phildini** [comment]
if you could "unlock" the ability to change your name by having to take an action in the greeting room, that would be cool and on-brand
