### ISSUE TITLE
Whisper sidebar doesn't respect name changes

### ISSUE THREAD

**Issue by MoyTW** [lazerwalker/azure-mud#236]
May or may not be the same issue as #205 

1. Profile change is not respected
2. Whispers to the user who changed their name will be met with `{name} is not online...`

This occurs when:
* `Alice` brings up the profile  `Bob`
* `Bob` changes username to `Eve`
* `Alice` tries to message `Bob`/`Eve`

**Comment by lazerwalker** [comment]
This is because, even though username updates (and other minimal profile data updates) get sent in real-time over SignalR, the profile data we're using to show the active profile/whisper sidebar is unconnected from the userMap data where the new data exists.

Probably the easiest fix: the sidebar currently just takes in the current profile to show. If it takes in both that and the userMap data for that user, and renders whatever it can based on userMap data, it will auto-update.

**Comment by lazerwalker** [comment]
We'll also need to assume userMap data may not exist, and fall back to profile data if not, since offline users won't have userMap data and we support /looking at offline users.

**Comment by lazerwalker** [comment]
The linked commit miiiight fix this issue in some cases. Worth testing.

**Comment by lazerwalker** [comment]
To confirm: someone's header name is now fixed, but their name in previously-sent whispers won't. I believe the above-mentioned fix will work.
