### ISSUE TITLE
If the window is taller than your window, any state refresh? sends you all the way back up

### ISSUE THREAD

**Issue by MoyTW** [lazerwalker/azure-mud#291]
Reproducing with send messages:
1. Go to the theater or a showcase room
2. Scroll aaaaallll the way down
3. Type something
4. OH NO now you're at the top!

Reproducing with scroll message:
1. Go to the theater or a showcase room
2. Scroll aaaaallll the way down
3. Scroll your chat up
4. OH NO now you're at the top!

Reproducing with receiving messages:
1. go to blah blah with 2 accounts
2. scroll both to bottom
3. send message on 1
4. whoops BOTH are at the top lol

**Comment by MoyTW** [comment]
Ok it's from here: https://github.com/lazerwalker/azure-mud/blob/71798907e4a2469afdf717be48e55b2c9b4c5735/src/components/MapView.tsx#L64 - I commented that line and it went away.

**Comment by MoyTW** [comment]
I assume that the fact that this is happening means the empty array at the end of the `useEffect` doing...whatever it's supposed to be doing.

**Comment by lazerwalker** [comment]
ohhh *facepalm*.

So, the `[]` means "only run this code block the first time this component is rendered, as opposed to every time". This is desired for the main map, since it will re-render frequently as users move rooms and it updates its presence counts and we don't want to snap back to the current room every time that happens. 

In theory, we don't want that behavior on the mini-map, because if you click a new room to go there, we want to re-render the map to focus on wherever you've just moved to. We could switch the mini-map to use the `[]` behavior and find some way to manually re-focus it every time we hit the move room reducer path, but that feels very un-React-y. 

The "proper" solution is trying to figure out the correct "scroll to this element" function that will scroll the map view relative to its parent element, but won't scroll the entire page. I suspect such a function exists, and/or might be an option we can pass into `scrollIntoView`?

**Comment by lazerwalker** [comment]
It doesn't obviously look like what we want exists, but it wouldn't be a lot of work to replace the clickable area's `scrollIntoView` with manually calculating the scroll point we want and just calling `scroll` on the mini-map div itself. I can do that later.

**Comment by lazerwalker** [comment]
The left-field weird design change we could make instead is pin the mini-map to always be on the bottom-left corner of the screen, even as you scroll. This would make it feel more like a game UI mini-map, and it always being on-screen would have the funny side effect of also not triggering the undesirable screen-wide scroll without changing the scroll code.

**Comment by MoyTW** [comment]
`pin the mini-map to always be on the bottom-left corner of the screen, even as you scroll` tbh if it's easy 'nuff to do we should do this with the sidebar AND profile view, since if you scroll the sidebar down the left side is just...wasted space.

**Comment by MoyTW** [comment]
In fact we should definitely do that if we have time.

**Comment by lazerwalker** [comment]
Sidebar should be fixed in place now, which should fix this.
