### ISSUE TITLE
Make the profile creation/edit page look pretty

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/azure-mud#75]
1. Make it look better
2. Consider if the list of fields we have are the correct ones.

**Comment by lazerwalker** [comment]
There's a broader question about whether this is the correct list of fields for us to be getting, but at a basic level this could look a lot prettier.

This is 100% HTML and CSS, so this could be a great task for somebody who feels relatively visual design-y.

I think this should probably have text descriptions for each field. I'm happy to help jam on these.

**Comment by annie** [comment]
i can take a stab at this one!

**Comment by lazerwalker** [comment]
Awesome! :D

**Comment by lazerwalker** [comment]
Just to call out explicitly: this now looks great (🎉) but still needs a pass on which fields are the correct ones, and writing longer-form descriptions for what they are.

**Comment by annie** [comment]
i can take another pass at this -- i think the fields are right for the most part, but i may try renaming "Description" to "Bio" or something like that. i'd never played a MUD before, so i initially thought "Description" meant a physical description of my character in the game lol

**Comment by lazerwalker** [comment]
No, you had it 100% right for description — not described at all in the current form, but I was imagining people would describe how their avatars look in the space :)

I think I'd like to take this, if you don't mind. I have some specific thoughts about the least-confusing way to present this to folks I'd like to toy with.

**Comment by lazerwalker** [comment]
I tried framing this as a "name badge", and added some descriptions to each field. Thoughts?

![Screen Shot 2020-08-19 at 11 22 34 PM](https://user-images.githubusercontent.com/821238/90713210-dff8e000-e272-11ea-89b0-6c9633b55f36.png)

Other things on my mind:
* Right now, we auto-add your Twitter handle to your bio. We probably want to let people add their own handle instead of just the one they logged in with, maybe?
* There's room for a lot of other fun fields (e.g. their "character class", in Alexei's parlance from last year). I'm not sure how much whimsy we should add vs them just adding more fields for people to fill out.

**Comment by kawa-kitsuragi** [comment]
I actually prefer the auto-add your Twitter handle - less things for the end user to type, since we're requiring Twitter login anyway unless someone actually changes the authentication options. 

I am very biased pro-Alexei here, I did love the 'character class' from last year, I think it'd be a fun nod and a good way to make conversation - but I do wonder if it'd be a bit hard to describe on our limited amount of space for folks who didn't see her talk last year. Indeed, one of the fun things about it last year was that it came organically from what inspired people at the con - if we can change it mid-flight like that reacting to this year's content, that'd be ideal. 

Also relatedly - do we want to make pronouns required?

**Comment by lazerwalker** [comment]
My assumption was that we should prepopulate the Twitter field, rather than either have it be blank or (as it currently is) automatically forcibly set to whatever you logged in as.

Yeahhh, I think the character classes is a lot like the "it's set at GitHub" thing in that this is fun for old-timers and baffling for anyone new.

Right now, no fields are required. I think it's important that pronouns be optional — this can be confusing and scary for questioning folks, and even the act of writing "ask me" or something like that can be a lot. That runs the risk of some asshole cis dudes not putting anything in, but that's a social problem to solve.

**Comment by annie** [comment]
a few thoughts:
- i think for privacy reasons, it'd be nice if we made it optional to display your Twitter handle. even though we require Twitter for login, some folks might not want to display it
- if we were to allow people to add a Twitter handle that they didn't log in with, would we require them to authenticate that handle? otherwise people could just add Twitter handles that don't belong to them / potentially try to impersonate someone else
- small UI thing - you might want to try giving the field descriptions a smaller font-weight or maybe a subtler color. the visual hierarchy is a bit confusing to me at the moment

**Comment by lazerwalker** [comment]
* Yeah, absolutely agree about making it optional to display your Twitter handle. My thought was that if we just prepopulate a normal text field with whatever you've logged in as, just letting people delete it is probably fine?

* I think I'm not particularly worried about authenticating handles? Most online spaces that let you enter social media handles

* Re: both of those previous points: maybe I'm wrong and we should just say "here's your Twitter handle you logged in as, do you want to display it publicly or not?"

* Ahh, good call on the visual hierarchy. I'm happy to take a stab at that tonight, but also happy if you want to clean things up. I hope the changes I made don't feel like I was stepping on the toes of your earlier work! Absolutely not my intention, but apologies if that ended up happening regardless.

**Comment by annie** [comment]
my vote would be for "here's your Twitter handle you logged in as, do you want to display it publicly or not?"

and omg no worries at all!! i absolutely did not think that what i previously pushed was gonna be the final product. also y'all know much more about the history / intent of this space than i do 😅  i'm just happy to contribute

**Comment by lazerwalker** [comment]
Ahh, good catch, thanks!

**Comment by lazerwalker** [comment]
I fixed scrolling as suggested, happy to call this done for the purposes of the preview.
