### ISSUE TITLE
Experiment with embedding Streamtext.net captions in the Theatre

### ISSUE THREAD

**Issue by lazerwalker** [lazerwalker/azure-mud#90]
I'm imagining we'd embed an iframe below the Twitch iframe. I'm not sure if this will look good / be acceptable, but it's worth trying!

https://www.streamtext.net/player/transcript?event=IHaveADream is a sample URL you can use for testing.

**Comment by apepers** [comment]
I did a bit of experimenting and the embedding it in an iframe is very easy - the problem is that as the text continues to grow, it won't auto-scroll to see the new text. I messed around with some CSS hacks but wasn't able to find a way to get it to keep the latest text in view, especially since really it's not text, it's just viewing a webpage.

My hacky brain is going to 'create a function on a timer that forces a scroll to the bottom' but that's awfully messy - any other ideas?

**Comment by lazerwalker** [comment]
Hmmm, weird! Bangbangcon embedded a StreamText site onto their viewing page, so I'll ask them if they had a trick.

Worst case scenario, I suspect it's fine to either bake open captions directly into the video feed (although this may be tough with StreamYard) and/or only provide a separate link for people to keep captions open I'm a separate tab.

**Comment by lazerwalker** [comment]
Aha! It looks like there's a configurable scrolling option: https://streamtext.zendesk.com/hc/en-us/articles/210923103-Controlling-the-streaming-text-page-display
